package com.company;

import java.util.Scanner;
/*Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
 exceed four million, find the sum of the even-valued terms.
 */

public class Main {

    public static void main(String[] args) {


        Scanner veriAl = new Scanner(System.in);
        System.out.println("Kaç sayıya kadar...");
        double ilk = 0;
        double ikinci = 1;
        double toplam = 0;
        double çift = 0;
        double adım = veriAl.nextInt();

        for (int i = 0; i < adım - 2; i++) {
            toplam = ilk + ikinci;
            if (toplam % 2 == 0 && toplam < 4000000) {
                çift += toplam;
                System.out.println(çift);
            }
            ilk = ikinci;
            ikinci = toplam;
        }
    }
}

